/**
 * Session persistence.
 *
 * A shop that refreshes mid-job should not lose its setup. Everything cheap to
 * store is stored: job paperwork, production settings, size, per-ink names,
 * colors, mesh, halftones and print order.
 *
 * The artwork raster is deliberately NOT persisted. A production-size file is
 * tens of megabytes and would blow the localStorage quota, so the restore path
 * tells the artist plainly that the artwork must be re-dropped rather than
 * silently coming back with an empty canvas.
 */

import type {
  ExportSettings, HalftoneSettings, InkHalftone, InkSeparation, JobMetadata,
  MaskSettings, ProductionSettings, ProductionSize,
} from "@/lib/types";
import { readJson, writeJson, removeKey, STORAGE_KEYS } from "./storage";

/** Per-ink state worth restoring. Masks are regenerated by re-separating. */
export interface PersistedInk {
  id: string;
  name: string;
  displayColor: string;
  type: string;
  order: number;
  visible: boolean;
  mesh: number;
  settings: MaskSettings;
  halftone: InkHalftone;
}

export interface PersistedUnderbase {
  choke: number;
  strength: number;
  removeUnderBlack: boolean;
  highlightWhite: boolean;
}

export interface PersistedSession {
  version: 1;
  savedAt: string;
  metadata: JobMetadata;
  settings: ProductionSettings;
  productionSize: ProductionSize;
  halftone: HalftoneSettings;
  exportSettings: ExportSettings;
  underbase: PersistedUnderbase;
  removeBackground: boolean;
  /** Empty until a separation has been produced. */
  inks: PersistedInk[];
  printOrder: string[];
  /** Name of the file that produced this session, to prompt a re-upload. */
  artworkFileName: string | null;
  artworkPixelWidth: number | null;
  artworkPixelHeight: number | null;
  presetId: string | null;
}

export function persistInk(ink: InkSeparation): PersistedInk {
  return {
    id: ink.id,
    name: ink.name,
    displayColor: ink.displayColor,
    type: ink.type,
    order: ink.order,
    visible: ink.visible,
    mesh: ink.mesh,
    settings: ink.settings,
    halftone: ink.halftone,
  };
}

export function saveSession(session: PersistedSession): boolean {
  return writeJson(STORAGE_KEYS.session, session);
}

export function loadSession(): PersistedSession | null {
  const raw = readJson<PersistedSession | null>(STORAGE_KEYS.session, null);
  if (!raw || typeof raw !== "object") return null;
  if (raw.version !== 1) return null;
  // Guard against partially-written or hand-edited state.
  if (!raw.settings || !raw.productionSize || !raw.metadata) return null;
  return {
    ...raw,
    inks: Array.isArray(raw.inks) ? raw.inks : [],
    printOrder: Array.isArray(raw.printOrder) ? raw.printOrder : [],
  };
}

export function clearSession(): void {
  removeKey(STORAGE_KEYS.session);
}

/**
 * Re-applies persisted per-ink edits to a freshly separated plan.
 *
 * Matching is by ink id. A re-separation with the same settings produces the
 * same ids, so a restored session lines up; when it does not (different
 * artwork, different screen count) the unmatched inks simply keep the
 * engine's values rather than being force-fitted to stale state.
 */
export function reapplyInkState(
  inks: InkSeparation[],
  persisted: PersistedInk[],
): { inks: InkSeparation[]; matched: number } {
  if (persisted.length === 0) return { inks, matched: 0 };
  const byId = new Map(persisted.map((p) => [p.id, p]));
  let matched = 0;

  const next = inks.map((ink) => {
    const p = byId.get(ink.id);
    if (!p) return ink;
    matched++;
    return {
      ...ink,
      name: p.name,
      displayColor: p.displayColor,
      visible: p.visible,
      mesh: p.mesh,
      halftone: p.halftone,
      // Mask-affecting settings are restored but the caller must re-derive the
      // mask from them; leaving them here keeps the UI consistent.
      settings: p.settings,
    };
  });

  return { inks: next, matched };
}
